// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace ASPNETCore5Demo.Models
{
  public partial class ContosoUniversityContext : DbContext
  {
    public virtual DbSet<DepartmentDropDown> DepartmentDropDown { get; set; }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
    {
      // 註冊自訂義的model(非db model)，避免Generator重跑後把額外註冊Model覆蓋
      modelBuilder.Entity<DepartmentDropDown>(entity =>
            {
              entity.HasNoKey();
            });
    }
  }
}